"""Параметры RAG, вынесенные в отдельный файл для наглядности."""

CHUNK_SIZE = 500
CHUNK_MIN_SIZE = 100
CHUNK_OVERLAP = 0.2
TOP_K = 3
HISTORY_TURNS = 3
WARM_LEAD_HISTORY_WINDOW = 4
PRICE_RETRIEVAL_K = 5
SERVICE_RETRIEVAL_K = 6
ENABLE_RERANKER = False
PRICE_KEYWORD_WEIGHT = 0.7
PRICE_EMBEDDING_WEIGHT = 0.3
SERVICE_KEYWORD_WEIGHT = 0.5
SERVICE_EMBEDDING_WEIGHT = 0.5
FAQ_KEYWORD_WEIGHT = 0.3
FAQ_EMBEDDING_WEIGHT = 0.7
